---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.23.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      ingressClass: internal
      replicaCount: 2
      extraEnvs:
      - name: TZ
        value: America/New_York
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.130
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      config:
        # ssl-protocols: "TLSv1.3 TLSv1.2"
        # Setting use-proxy-protocol to true will break the proxy
        use-proxy-protocol: "false"
        proxy-body-size: "0"
        use-forwarded-headers: "true"
      resources:
        requests:
          memory: 250Mi
          cpu: 100m
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: false
