---

all:
  children:
    # Master group, do not change the 'master' name
    # hosts should match the filenames in 'host_vars'
    master:
      hosts:
        k8s-master:
        # k8s-master-a:
        # k8s-master-b:
        # k8s-master-c:
    # Worker group, do not change the 'worker' name
    # hosts should match the filenames in 'host_vars'
    worker:
      hosts:
        k8s-worker-a:
        k8s-worker-b:
        k8s-worker-c:
        # k8s-worker-d:
        # k8s-worker-e:
