---
version: '3'

includes:
  ansible: .taskfiles/Taskfile_ansible.yml
  blocky: .taskfiles/Taskfile_blocky.yml
  deps: .taskfiles/Taskfile_{{OS}}.yml
  renovate: .taskfiles/Taskfile_renovate.yml
  secrets: .taskfiles/Taskfile_secrets.yml
