---

- name: boot | set cmdline options
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory apparmor=0 mitigations=off max_loop=32\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory apparmor=0 mitigations=off max_loop=32'
  when: ansible_architecture | regex_search('arm|aarch')
