---

# Configure a registry mirror, useful for having a pull-through cache
mirror_registry:
  address: "https://registry-cache.devbu.io"

# Configure private registries
private_registries:
- address: "https://registry.devbu.io"
  username: "admin"
  password: "password"
