---

- hosts:
  - master
  - worker
  - storage
  become: true
  gather_facts: true
  tasks:

  #
  # Turn off master and worker devices in 2 minutes
  #

  - name: turn off master nodes
    # command: /sbin/shutdown -h 2
    command: /sbin/shutdown --help
    when: "'master' in group_names"

  - name: turn off worker nodes
    # command: /sbin/shutdown -h 2
    command: /sbin/shutdown --help
    when: "'worker' in group_names"

  #
  # Turn off NAS devices in 5 minutes
  #

  # Qnap devices do not have /sbin/shutdown and
  # instead use busybox /sbin/poweroff
  - name: turn off storage nodes
    # command: /sbin/poweroff -d 300
    command: /sbin/poweroff --help
    when: inventory_hostname == "nas-rocinante"

  - name: turn off storage nodes
    # command: /sbin/shutdown -h 5
    command: /sbin/shutdown --help
    when: inventory_hostname == "nas-serenity"
