---

#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration
#

# Define the host as a control plane node
k3s_control_node: true

# k3s settings for master nodes node
k3s_server:
  node-ip: "{{ ansible_host }}"
  # tls-san:
  # - opnsense.devbu.io
  docker: false
  flannel-backend: 'none' # This needs to be in quotes
  disable:
  - flannel
  - traefik
  - servicelb
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "10.12.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "10.21.0.0/16"
